### ISSUE TITLE
Upload speed

### ISSUE THREAD

**Issue by tixtix** [jlesage/docker-crashplan#10]
Any tips on increasing the upload speed?

In the last month or so my upload speed dropped to barely ~150 KB/s where previous months on average upload was as fast as 2MB/s, sometimes reaching almost 4MB/s but never dropping below 1.5 MB/s

Data de-duplication is set to Minimal and Compression is OFF

My backup is over 17TB and is uploaded in 85%

Any ideas on how to increase the upload speed?

**Comment by jlesage** [comment]
See the discussion at https://github.com/jlesage/docker-crashplan-pro/issues/83

If calculating the effective upload speed yourself still give something low, then I would suggest to contact CrashPlan support to see if they can help.
