### ISSUE TITLE
Dockerised Crashplan file selection not working

### ISSUE THREAD

**Issue by xave99** [jlesage/docker-crashplan#11]
Hi

I've installed the Crashplan docker on my QNAP NAS (firmware v 4.3.4) using the script below but am not able to select the backup folders properly (I have 4). The 4 folders themselves appear in the Crashplan selection list, but they do not show any subfolders or files. (Funnily enough, other system folders in which I am not interested in backing up do drop down to show subfolders and files.) When I add them and perform a backup, the backup completes instantly with 0 files.

My script is:

docker run -d \
       --name=crashplan \
       -p 5800:5800 \
       -e user_id=0 \
       -e group_id=0 \
       -v /share/CE_CACHEDEV1_DATA/Container/container-station-data/config/crashplan:/config:rw \
       -v /share/CE_CACHEDEV1_DATA:/storage:ro \
       jlesage/crashplan

![screen1](https://user-images.githubusercontent.com/40517608/41808645-1c93f59c-76d0-11e8-8038-d6d40803ad75.png)

Also, some other information that may or may not be relevant:

1. After adopting a previous computer, I had to re-enter the Passphrase encryption key which I had used previously for the files.
2. My QNAP NAS previously ran Crashplan as a QPKG on the NAS with no problems.  See screenshot below of what the folder selection should look like:

![screen2](https://user-images.githubusercontent.com/40517608/41808688-dc1f6004-76d0-11e8-8e5f-941153c9e48b.png)

Was thinking it might be a permissions issue but adding user_id and group_id=0 did not change anything. In QNAP's shared folder permissions configuration, experimented with giving "guest" read only access for the "backup" folder to see but that still not allow the Crashplan GUI to see any files or subfolders for "backup".

Would be very grateful for some help, I've been trying to figure this out for 10 hours straight and have a huge headache!

Xavier

**Comment by jlesage** [comment]
Make sure that the variables names `USER_ID` and `GROUP_ID` are in uppercase, else they don't apply.

**Comment by xave99** [comment]
Wow, what a rookie mistake on my part, probably because I'm a rookie at this.. THANKS! Putting the variable names in uppercase solved the problem and I can access the subdirectories now!
