### ISSUE TITLE
Can't upgrade - container old?

### ISSUE THREAD

**Issue by gkyriazis** [jlesage/docker-crashplan#13]
Hello..

A few days ago, my crashplan pro process asked me to update (to 6.9.2), but the container hasn't been updated for 5 months.  Does it need to be updated?

Thank you!

**Comment by jlesage** [comment]
Yes.  The last container image version has been released 10 days ago.  See https://github.com/jlesage/docker-crashplan-pro/releases

Btw, you are un the wrong project.  The one for the PRO version is located at https://github.com/jlesage/docker-crashplan-pro

**Comment by gkyriazis** [comment]
Thank you!
