### ISSUE TITLE
QNAP Docker Solution?

### ISSUE THREAD

**Issue by jarms03** [jlesage/docker-crashplan#14]
How can I use Crashplan Pro on my QNAP TVS-872XT?

**Comment by jlesage** [comment]
I would suggest to read on how to use Docker on QNAP.  Maybe this can be a good start:
https://www.qnap.com/en/how-to/tutorial/article/how-to-use-container-station/

**Comment by vbc4ejyg** [comment]
I use jlesage/docker-crashplan-pro on my TS-877 so the answer is most certianly.

https://github.com/jlesage/docker-crashplan-pro
