### ISSUE TITLE
Memory Settings

### ISSUE THREAD

**Issue by neu5ron** [jlesage/docker-crashplan#15]
First off, thank you for this project! This project has actually help save me in ways I can't explain.

I just wanted to open this issue for anybody else wondering what memory/heap settings are not taking the input form environment variable. I even tried few other things. Here is what I tried and what worked.

**What worked:**
open gui, press "Ctrl + Shift + C", then input `java mx 8192, restart`

**What did not work:**
- setting environment variable in docker run, using `-e CRASHPLAN_SRV_MAX_MEM=8192M`
- modifying `/docker/appdata/crashplan-pro/conf/bin/vars.sh` by adding `SET CRASHPLAN_SRV_MAX_MEM=8192M`
- modifying `/docker/appdata/crashplan-pro/conf/jvm_args` to be `-Xmx8192M`

**Comment by jlesage** [comment]
Use of `CRASHPLAN_SRV_MAX_MEM` is now fixed with the latest image :)
