### ISSUE TITLE
Looks like there is a new update to the crashplan client

### ISSUE THREAD

**Issue by DavidLaidlaw** [jlesage/docker-crashplan#16]
Thanks!

**Comment by jlesage** [comment]
This container (CrashPlan for Home) is not longer usable.  Are you looking for the CrashPlan PRO version ?

**Comment by DavidLaidlaw** [comment]
My mistake, I did mean to put this on the CrashPlan PRO version.  It also seems like CrashPlan has managed to get going again on my machine, despite earlier error messages about being unable to update.  I'll see if I can close this myself, but that does not work, please feel free to close.  Thanks!
