### ISSUE TITLE
Latest update has broken this container

### ISSUE THREAD

**Issue by neuralcpu** [jlesage/docker-crashplan#4]
Hi,

After Code42's latest update, I just get a black screen when trying to VNC to the GUI. I haven't had much time to investigate yet, but there appears to be an attempted update to UI, as well as the CrashPlan java application.

If you require further analysis, please let me know. I'll update this anyway with my detailed findings ASAP.

**Comment by jlesage** [comment]
Hello,
This container can't update itself.  Any attempt from CrashPlan to download updates will fail.
If you are using the latest container image, you will have the latest CrashPlan version.

**Comment by neuralcpu** [comment]
Thank you jlesage. I've downloaded the latest version of this container and I have no problem. 

I must have just missed the latest upload somehow.

**Comment by jlesage** [comment]
By curiosity, were you running the container as root (user_id = 0)?
