### ISSUE TITLE
CRASHPLAN_SRV_MAX_MEM - Not respected in crashplan-pro

### ISSUE THREAD

**Issue by returntrip** [jlesage/docker-crashplan#6]
Thanks for the great image!

I believe that CRASHPLAN_SRV_MAX_MEM  is not being respected.
I have set it in my docker-compose to 2048M but I see that the the real memory consumption is 3.3GB (for 600GB of files). Initially I had 2.5TB of backup data and crashplan pro would use 8GB of RAM :)

Is there anything I can check to see what is causing this issue?

**Comment by jlesage** [comment]
Is the 3.3GB memory consumption for the whole container?  Don't forget that `CRASHPLAN_SRV_MAX_MEM` is the limit for the engine only.  The UI, which is a different process, also consume memory.

The way to verify that the configured value is properly applied is to look at `bin/run.conf`, located in the configuration directory of the container.  Look for the `-Xmx` argument, which is followed by the memory limit.  For example, you could have something like `-Xmx2048m`.

**Comment by returntrip** [comment]
Thanks for the quick reply. I have checked `run.conf` and I can see that `-Xmx2048m` is set correctly, however I saw an error on the Crashplan client saying that the app had crashed because it had run out of memory and to increase the memory by using `CRASHPLAN_SRV_MAX_MEM`.

I have set the memory to `3072M` and see `-Xmx3072M` in `run.conf`. I am monitoring to see how much total memory is the whole container using, at the moment it is using 3.1GB RAM at container level.

Isn't it strange tho that with 2.5TB of data and `CRASHPLAN_SRV_MAX_MEM` set to `2048M` the container used memory would shoot to 8GB RAM?

**Comment by jlesage** [comment]
With 2.5TB of data and a memory limit of 2048M, I would expect the engine to crash.  So not sure where all the consumed memory comes from.  We would need to check the system while in this state to see what's happening.

**Comment by returntrip** [comment]
I have cleared 2TB of data now :( to overcome this issue. I regret it tho. 

I see that you also have a Cloudberry docker image. Do you find Cloudberry to be better than Crashplan?
Unsure if we can converse here or if you prefer to switch to a different communication channel.

**Comment by jlesage** [comment]
CloudBerry requires a little bit more work to setup because it works with a lot of storage providers.  There is also sometime little glitches, where it reports that a file failed to be backup, but succeed on the next one.  However, CloudBerry usually fixes reported problems in a reasonable time frame.

But at the end it can be a good alternative to CP.  Also, when used with Backblaze B2, it can be less expensive depending on the size of your backup.

**Comment by returntrip** [comment]
Unfortunately I am now at 4.80GB Consumption for the container. I also got the following message on the CrashPlan interface: CrashPlan for Small Business' memory consumption comes close to its limit" and I get told to increase the `CRASHPLAN_SRV_MAX_MEM` variable

At the moment i have a total of 590GB of data in my backup and a `CRASHPLAN_SRV_MAX_MEM` of `3072M`

Anything I could check to see what is sucking all the memory?

This is the main offenders within the container:

``` 
 PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
  810   529 root     S    6863m  40%   0  20% /usr/local/crashplan/jre/bin/java -Dfile.encoding=UTF-8 -Dapp=CrashPlanService -DappBaseName=CrashPlan -Xms20m -Xmx3072M -Dsun.net.inetaddr.ttl=300 -Dnetworkaddress.cache.ttl=300 -Dsun.net.inetaddr.negative.ttl=0 -Dnetworkaddress.cache.negative.ttl=0 -Dc42.native.md5.enabled=false -classpath /usr/local/crashplan/lib/com.backup42.des
24452   528 root     S    1127m   7%   2   0% /usr/local/crashplan/electron/crashplan
25650 24496 root     S    1125m   7%   0   0% /usr/local/crashplan/electron/crashplan --type=renderer --no-sandbox --primordial-pipe-token=60F4C9F137C69045BDD285DB8F448278 --lang=en-US --app-path=/usr/local/crashplan/electron/resources/app.asar --node-integration=true --hidden-page --enable-pinch --num-raster-threads=2 --enable-main-frame-before-activation --content-image-textu
24496 24452 root     S     317m   2%   0   0% /usr/local/crashplan/electron/crashplan --type=zygote --no-sandbox
10835 10827 root     S     110m   1%   3   0% yad --fixed --center --title CrashPlan for Small Business --window-icon /opt/novnc/images/icons/master_icon.png --borders 10 --image dialog-warning --image-on-top --text <b>CrashPlan for Small Business's memory consumption comes close to its limit.</b> --form --field More than 75% of allocated memory is used.  Consider increasing me
17359   532 root     S    87704   1%   2   0% /usr/bin/openbox
```

**Comment by ljm42** [comment]
It is the total size of the backup that matters, not the amount that is left to backup.

See this:
https://support.code42.com/CrashPlan/6/Troubleshooting/Adjust_Code42_app_settings_for_memory_usage_with_large_backups
Although in my experience it doesn't take as much RAM as they say it will.

**Comment by returntrip** [comment]
I should correct mysel, the backed up data is 590GB. That is the total amount of data that has already been backed up. I have only 1GB pending.

**Comment by returntrip** [comment]
I will close this issue because I was misled by an older version of`ctop`  (0.6.1), which was reporting memory consumption of containers including caches. I saw  9GB RAM usage on this version!

See https://github.com/bcicen/ctop/issues/84 for more details

Now I have `ctop` 0.7 and I see that the RAM consumption is 3.80GB 

When I use `docker stats --no-stream` I see around 3.9GB of RAM usage, so I think we should be good (still what a memory hog!!!):
```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
859f3f070382        crashplan-pro       8.30%               3.789GiB / 15.54GiB   24.39%              147MB / 11.4GB      17.2GB / 1.14GB     167
```
