### ISSUE TITLE
CrashPlan command-line interface not working

### ISSUE THREAD

**Issue by ptlambert** [jlesage/docker-crashplan#7]
CrashPlan Home v4.8.4 includes a command-line interface that is accessed by double-clicking the green icon in the upper-right corner of the desktop application.  In a non-containerized installation, the CLI window will include both a text-entry area at the top and a listing underneath of available commands.

When I double-click that icon in the container (using the latest version v1.6.3), I do get the text entry field, but instead of a command listing there is just an empty pane.  Also, no matter what command I enter in the text area, after pressing Enter the entire window disappears and the command seems to be ignored.

**Comment by jlesage** [comment]
Even if the window disappear, the command should still be ran.

Do you know which one is not working?

**Comment by ptlambert** [comment]
Actually, I was trying commands that require a working console window for feedback, like "help", "version", "guid", etc.  Those don't return any results due to the disappearing window issue.

But as you suggested in Issue #8, commands that manipulate the service state do work!  So **shutdown** (stop,exit) and **restart** are working.

Perhaps you can add a note about this in your container documentation page on Docker Hub?

Thanks!

**Comment by jlesage** [comment]
Sure I will add something to the README for this.
