### ISSUE TITLE
Can't close Desktop app after logging in

### ISSUE THREAD

**Issue by ptlambert** [jlesage/docker-crashplan#8]
I've got CrashPlan for Home v4.8.4 configured to require a password to open the CrashPlan Desktop app.  Among other things, this helps to overcome the very weak authentication in VNC due to the 8 character password limitation.

The CP Desktop app includes no provision to explicitly logout.  In a non-containerized installation, closing the app window on the host effectively logs out of the current app session.

With your current container implementation (v1.6.3), the Desktop app window is exported as the VNC root.  Closing the VNC window does not actually close the desktop app -- at least not when accessing the app via a browser at port 5800.

So... if I logon to the Desktop app, then close the VNC window, then open it again, the app remains open.  This means that following initial logon to the app, my CrashPlan settings and data are at the mercy of that very weak 8 character password limitation in VNC.

The only way I've found to workaround this issue is to stop and start the container.

Perhaps you can find a way to export a parent system window as a wrapper around the desktop app window, with the usual titlebar and close box, etc. thereby giving us the ability to explicitly close the window?  Doing this (if possible) might also solve the problem I've reported in Issue #7, with the CLI window not displaying or working correctly.

P.S. Thanks for your time and effort on this project!  This container will be very useful for me, even if no workaround can be found for this issue.

**Comment by jlesage** [comment]
What you can do is set the environment variable `KEEP_APP_RUNNING`to `1` and close CrashPlan by running the `exit` cli command.  Even if this command closes CP, the container will not be shut down because of the environment variable (CP will be restarted).

**Comment by ptlambert** [comment]
FYI, I am using your container v1.6.3 under DSM on Synology NAS.  The default environment variables there include `KEEP_GUIAPP_RUNNING` but not `KEEP_APP_RUNNING`.  I assume these reference the same CrashPlan Desktop app?  And it appears the variable is set to `1` by default.

So as I mentioned in closing Issue #7, the CrashPlan CLI command `exit` _does_ work.  And running that command does indeed solve this problem. The `restart` command works just as well, and doesn't rely on that variable being set one way or another.

This definitely closes any issues I had with using the container.  I hope you can add a section to your container documentation addressing this issue and workaround.

Thanks again!

**Comment by jlesage** [comment]
Yes, both variables are doing the same thing.  However, `KEEP_GUIAPP_RUNNING` is deprecated and should not be used.  I realized that this variable is still set in the `Dockerfile` and it's for this reason that it's part of default environment variable in Synology.  I will fix that, thanks for this comment!
