### ISSUE TITLE
No connection to crashplan central

### ISSUE THREAD

**Issue by Bagu** [jlesage/docker-crashplan#9]
Hello, i have an old crashplan wich is valid for 3 month on a synology nas with 8GB Ram.
But since 5 days, the docker can't connect to crashplan central.

I update the registry, clear the image, try to clear the cache without succes.
What can i do to make it work again ?

Thanks

(Here is the exact issue : https://support.code42.com/CrashPlan/4/Troubleshooting/Cannot_connect_to_destination )

**Comment by jlesage** [comment]
Did you look at `log/service.log.0` for any clues?  You can find this file in the appdata folder of the container.
This error can occur when the container is not able to resolve `central.crashplanpro.com`.  You can try to see if it's the case by executing `docker run <container name> nslookup central.crashplanpro.com`.

**Comment by Bagu** [comment]
nslookup to central.crashplanpro.com work well : 
Non-authoritative answer:
Name:   central.crashplanpro.com
Address: 216.17.8.4
Name:   central.crashplanpro.com
Address: 216.17.8.47
Name:   central.crashplanpro.com
Address: 216.17.8.51
Name:   central.crashplanpro.com
Address: 216.17.8.48
Name:   central.crashplanpro.com
Address: 216.17.8.3

In log/service.log.0 there is only two relevant error : 
[04.26.18 01:12:20.639 INFO  2663_AUTH-32 backup42.service.peer.Authorizer] AUTH:: Error = CPErrors.Login.TOO_BUSY : []
05.25.18 21:47:19.624 INFO  69119_AUTH-1 backup42.service.peer.Authorizer] AUTH:: Error = CPErrors.Global.CPC_UNAVAILABLE : [central.crashplan.com:443]

**Comment by Bagu** [comment]
Ok, it's really a problem.

I decided to remove everything to get a clean install.
And after the full re-install, i can't log to the crashplan vnc interface.
I only get Crashplan logo with a red cross.

my command line is : 
docker run -d --name Crashplan -p 5800:5800 -e USER_ID=0 -e GROUP_ID=0 -e LANG=en_US.UTF-8 -e SECURE_CONNECTION=1 -e VNC_PASSWORD=mysecretpassword -v /volume1/docker/appdata/crashplan:/config:rw -v /volume1:/volume1:ro jlesage/crashplan
I'm on a synology. The container is up and running.

**Comment by jlesage** [comment]
Can you provide a screenshot of what your are getting?

**Comment by Bagu** [comment]
![crashplan](https://user-images.githubusercontent.com/41675/40858914-3cddd792-65e0-11e8-87eb-b8fe84c2f9b5.jpg)

Here it is.

**Comment by jlesage** [comment]
Can you try to clear your browser’s cache and/or try with another browser?

**Comment by Bagu** [comment]
Ok, since i clear the cache, it's little better : 

![crashplan](https://user-images.githubusercontent.com/41675/40860880-36204e1a-65e7-11e8-9ccd-26e062089480.jpg)

**Comment by jlesage** [comment]
Can you provide service.log.0?

**Comment by Bagu** [comment]
Yes, here it is.
**removed for privacy reason**

**Comment by jlesage** [comment]
You seem to have a DNS issue:

```
[06.01.18 20:03:18.943 WARN  DefaultGroup .code42.messaging.peer.PeerGroup] PG::DefaultGroup PeerException attempting to connect. RemotePeer-[guid=42, SERVER]; PeerConnectionState-[state=CONNECTING, mode=PRIVATE, currentAddressIndex=0, layer=2/2(Peer::NIO), connecting=2018-06-01T20:03:18:942, connected=0, disconnected=2018-06-01T20:03:16:947, attempts=0, connectActivity=2018-06-01T20:03:18:942, keepAliveSent=0, minRetry=25158, reconnectable, location=central.crashplan.com:443, transportPbK=null, transportPbKRequestable=true]; Session-null e=com.code42.peer.exception.PeerException: IOExcepton opening remote session. guid=42, remoteLocation=[[42@central.crashplan.com:443(server)], pbKRequestable=true], timeout=30000, java.io.IOException: Unexpected Exception in connect() for remoteAddress=central.crashplan.com:443, java.nio.channels.UnresolvedAddressException
```

Did you run the `nslookup`command inside the container (no on the host)?

**Comment by jlesage** [comment]
The address it can't resolve is `central.crashplan.com`.

**Comment by Bagu** [comment]
I try this : 
sudo docker run jlesage/crashplan:latest nslookup central.crashplan.com

I'm not sure it's the right command. But if this is the right command, i get this : 
nslookup: can't resolve '(null)': Name does not resolve

nslookup: can't resolve 'central.crashplan.com': Try again

So, if this is the right command, there is a problem.
Synology resolve well, but not docker container ?!?

**Comment by Bagu** [comment]
Ok, i uninstall crashplan AND docker.
And, after reinstalling it, everything ssem to work well and nslookup on central.crashplan.com inside docker work.

So it's a docker problem and not a crashplan problem.
Thank you very much for your help.

**Comment by jlesage** [comment]
Great, happy to see that it’s now working for you.
